# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy

on:
  push:
    branches: [main]

env:
  BASE_PATH: /ya-webadb

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - run: node common/scripts/install-run-rush.js install
      - run: node common/scripts/install-run-rush.js build --verbose

      - run: npx next export
        working-directory: ./apps/demo

      - run: touch apps/demo/out/.nojekyll

      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: apps/demo/out
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
